apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: helm-dependency
  namespace: argocd
spec:
  description: Project for helm-dependency example
  destinations:
  - namespace: argocd-apps
    server: https://kubernetes.default.svc
  sourceRepos:
  - '*'
