apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deploy-app-broken-hello-k8s
spec:
  destination:
    name: ''
    namespace: argocd-apps
    server: 'https://kubernetes.default.svc'
  source:
    path: ./
    repoURL: 'http://40.91.83.114/scm/repo/exercises/broken-application'
    targetRevision: HEAD
    directory:
      recurse: true
  project: hello-k8s
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
