apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deploy-helm-dependency-archive
spec:
  destination:
    name: ''
    namespace: argocd-apps
    server: 'https://kubernetes.default.svc'
  source:
    path: gitops/helm-archive/oauth2-proxy-4.2.2.tgz
    repoURL: 'https://github.com/paule1953/play-argocd.git'
    targetRevision: HEAD
    directory:
      recurse: true
    helm:
      version: v3
  project: helm-dependency
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
