apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deploy-helm-dependency
spec:
  destination:
    name: ''
    namespace: argocd-apps
    server: 'https://kubernetes.default.svc'
  source:
    path: helm-dependency
    repoURL: 'https://github.com/argoproj/argocd-example-apps.git'
    targetRevision: HEAD
    directory:
      recurse: true
  project: helm-dependency
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
